// packages/document-editor-angular/projects/my-lib/src/lib/components/margin-ruler/margin-ruler.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { DocumentReducerService } from '../util/document-reducer.service';
import { DOMEventHandlers } from '@mindfiredigital/canvas-editor';
import { CustomSliderVerticalComponent } from './custom-slider-vertical/custom-slider-vertical.component';
import { CustomSliderHorizontalComponent } from './custom-slider-horizontal/custom-slider-horizontal.component';
import { store } from '../util/store';
import useDebounce from '../util/useDebounce';

@Component({
  selector: 'lib-margin-ruler',
  standalone: true,
  imports: [CustomSliderVerticalComponent, CustomSliderHorizontalComponent],
  templateUrl: './margin-ruler.component.html',
  styleUrls: ['./margin-ruler.component.css'],
})
export class MarginRulerComponent implements OnInit {
  @Input() documentId!: string;
  verticalSlider: number[] = [];
  horizontalSlider: number[] = [];
  margins: any = [];

  constructor(private documentService: DocumentReducerService) {}

  ngOnInit(): void {
    if (!this.documentId) {
      console.error('Document ID is not provided.');
      return;
    }

    const documentState: any = store();

    if (!documentState || !documentState.margins) {
      console.error('Margins are not available in the document state.');
      return;
    }

    this.margins = useDebounce(documentState.margins, 500);

    if (this.margins.length) {
      this.verticalSlider = [-956, -100];
      this.horizontalSlider = [120, 696];

      if (!this.verticalSlider.length && !this.horizontalSlider.length) {
        DOMEventHandlers.setPaperMargins(this.margins);
      }
    }

    // this.documentService = new DocumentService();
  }

  handleChange(event: Event, value: number[]): void {
    const [bottom, top] = value;
    this.verticalSlider = value;

    const margin = [...this.margins];
    margin[0] = Math.abs(top);
    margin[1] = 1056 - Math.abs(bottom);

    DOMEventHandlers.setPaperMargins(margin);
    this.documentService.setDocumentMargins({ margins: margin });
  }

  handleChangeHorizontal(event: Event, value: number[]): void {
    const [left, right] = value;
    this.horizontalSlider = value;

    const margin = [...this.margins];
    margin[2] = left;
    margin[3] = 816 - right;

    DOMEventHandlers.setPaperMargins(margin);
    this.documentService.setDocumentMargins({ margins: margin });
  }
}

// packages/document-editor-react/component/src/components/MarginRuler/MarginRuler.tsx
import React, { useState, useEffect } from 'react';
import Stack from '@mui/material/Stack';
import { useDispatch, useSelector } from "react-redux";
import type { RootState } from "../../redux/store";
import { useDebounce } from "../../hooks/useDebounce";
import { DocumentState, setDocumentMargins } from "../../redux/documentReducer";
import { CustomSliderVertical, CustomSliderHorizontal, MarginRightArrow, MarginDownArrow, verticalMarks, horizontalMarks } from "./CustomSliderComponents";
import {
    DOMEventHandlers
} from "@mindfiredigital/canvas-editor";

export default function MarginRuler({ documentId }: { documentId: string | undefined }) {
    const dispatch = useDispatch();

    const document: any = useSelector(
        (state: RootState) => state.document
    ) as unknown as DocumentState;

    const [verticalSlider, setVerticalSlider]: any[] = useState<Array<Number>>([]);
    const [horizontalSlider, setHorizontalSlider]: any[] = useState<Array<Number>>([]);

    const margins: any = useDebounce(document.margins, 500);

    const handleChange = (e: any, value: Array<Number>) => {
        let [bottom, top]: any[] = value;
        setVerticalSlider(value);
        let margin = [...margins];
        margin[0] = Math.abs(top);
        margin[1] = 1056 - Math.abs(bottom);
        DOMEventHandlers.setPaperMargins(margin);
        dispatch(setDocumentMargins({ margins: margin }));
    }

    const handleChangeHorizontal = (e: any, value: Array<Number>) => {
        let [left, right]: any[] = value;
        setHorizontalSlider(value);
        let margin = [...margins];
        margin[2] = left;
        margin[3] = 816 - right;
        DOMEventHandlers.setPaperMargins(margin);
        dispatch(setDocumentMargins({ margins: margin }));
    }

    useEffect(() => {
        if (margins?.length && documentId) {
            setVerticalSlider([Math.abs(1056 - margins[1]) * -1, margins[0] * -1]);
            setHorizontalSlider([margins[2], 816 - margins[3]]);
            if (!verticalSlider.length && !horizontalSlider.length) {
                DOMEventHandlers.setPaperMargins(margins);
            }
        }
    }, [margins, documentId]);

    return (
        <React.Fragment>
            <Stack sx={{ height: "1056px", position: "absolute", left: "0px" }} direction="row">
                <CustomSliderVertical
                    orientation="vertical"
                    value={verticalSlider.length ? verticalSlider : [-956, -100]}
                    min={-1056}
                    max={0}
                    marks={verticalMarks}
                    onChange={handleChange}
                    step={24}
                    track="inverted"
                    scale={x => -1056}
                    size="small"
                    slots={{ thumb: MarginRightArrow }}
                    valueLabelDisplay="off"
                />
            </Stack>
            <Stack sx={{ height: "1px", position: "absolute", top: "-1px", width: "816px", left: "calc((100% - 811px) / 2)" }} direction="row">
                <CustomSliderHorizontal
                    orientation="horizontal"
                    value={horizontalSlider.length ? horizontalSlider : [120, 696]}
                    min={0}
                    max={816}
                    marks={horizontalMarks}
                    onChange={handleChangeHorizontal}
                    step={24}
                    size="small"
                    scale={x => 816}
                    slots={{ thumb: MarginDownArrow }}
                    valueLabelDisplay="off"
                />
            </Stack>
        </React.Fragment>
    )
}
