// packages/document-editor-react/component/src/components/MarginRuler/MarginRuler.tsx
import React, { useState, useEffect } from 'react';
import Stack from '@mui/material/Stack';
import { useDispatch, useSelector } from "react-redux";
import type { RootState } from "../../redux/store";
import { useDebounce } from "../../hooks/useDebounce";
import { DocumentState, setDocumentMargins } from "../../redux/documentReducer";
import { CustomSliderVertical, CustomSliderHorizontal, MarginRightArrow, MarginDownArrow, verticalMarks, horizontalMarks } from "./CustomSliderComponents";
import {
    DOMEventHandlers
} from "@mindfiredigital/canvas-editor";

export default function MarginRuler({ documentId }: { documentId: string | undefined }) {
    const dispatch = useDispatch();

    const document: any = useSelector(
        (state: RootState) => state.document
    ) as unknown as DocumentState;

    const [verticalSlider, setVerticalSlider]: any[] = useState<Array<Number>>([]);
    const [horizontalSlider, setHorizontalSlider]: any[] = useState<Array<Number>>([]);

    const margins: any = useDebounce(document.margins, 500);

    const handleChange = (e: any, value: Array<Number>) => {
        let [bottom, top]: any[] = value;
        setVerticalSlider(value);
        let margin = [...margins];
        margin[0] = Math.abs(top);
        margin[1] = 1056 - Math.abs(bottom);
        DOMEventHandlers.setPaperMargins(margin);
        dispatch(setDocumentMargins({ margins: margin }));
    }

    const handleChangeHorizontal = (e: any, value: Array<Number>) => {
        let [left, right]: any[] = value;
        setHorizontalSlider(value);
        let margin = [...margins];
        margin[2] = left;
        margin[3] = 816 - right;
        DOMEventHandlers.setPaperMargins(margin);
        dispatch(setDocumentMargins({ margins: margin }));
    }

    useEffect(() => {
        if (margins?.length && documentId) {
            setVerticalSlider([Math.abs(1056 - margins[1]) * -1, margins[0] * -1]);
            setHorizontalSlider([margins[2], 816 - margins[3]]);
            if (!verticalSlider.length && !horizontalSlider.length) {
                DOMEventHandlers.setPaperMargins(margins);
            }
        }
    }, [margins, documentId]);

    return (
        <React.Fragment>
            <Stack sx={{ height: "1056px", position: "absolute", left: "0px" }} direction="row">
                <CustomSliderVertical
                    orientation="vertical"
                    value={verticalSlider.length ? verticalSlider : [-956, -100]}
                    min={-1056}
                    max={0}
                    marks={verticalMarks}
                    onChange={handleChange}
                    step={24}
                    track="inverted"
                    scale={x => -1056}
                    size="small"
                    slots={{ thumb: MarginRightArrow }}
                    valueLabelDisplay="off"
                />
            </Stack>
            <Stack sx={{ height: "1px", position: "absolute", top: "-1px", width: "816px", left: "calc((100% - 811px) / 2)" }} direction="row">
                <CustomSliderHorizontal
                    orientation="horizontal"
                    value={horizontalSlider.length ? horizontalSlider : [120, 696]}
                    min={0}
                    max={816}
                    marks={horizontalMarks}
                    onChange={handleChangeHorizontal}
                    step={24}
                    size="small"
                    scale={x => 816}
                    slots={{ thumb: MarginDownArrow }}
                    valueLabelDisplay="off"
                />
            </Stack>
        </React.Fragment>
    )
}

// packages/document-editor-angular/projects/my-canvas-lib/src/lib/components/margin-ruler/margin-ruler.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { Store } from '@ngrx/store';
import { setDocumentMargins } from '../../store/document.actions';
import { selectDocumentMargins } from '../../store/document.selectors';
import { DOMEventHandlers } from '@mindfiredigital/canvas-editor';
import { CommonModule } from '@angular/common';
import { MatSliderModule } from '@angular/material/slider';
import { FormsModule } from '@angular/forms';
import {
  ChangeContext,
  NgxSliderModule,
  Options,
} from '@angular-slider/ngx-slider';
@Component({
  selector: 'app-margin-ruler',
  templateUrl: './margin-ruler.component.html',
  styleUrls: ['./margin-ruler.component.css'],
  standalone: true,
  imports: [CommonModule, MatSliderModule, FormsModule, NgxSliderModule],
  encapsulation: ViewEncapsulation.None,
})
export class MarginRulerComponent implements OnInit {
  verticalSlider: number[] = [100, 960];
  horizontalSlider: number[] = [135, 696];
  @Input() documentId!: string;

  verticalMarks = Array.from({ length: 12 }, (_, i) => ({
    value: i * 96,
    legend: i.toString(),
  }));

  horizontalMarks = Array.from({ length: 9 }, (_, i) => ({
    value: i * 96,
    legend: i.toString(),
  }));

  verticalOptions: Options = {
    floor: -1056,
    ceil: 0,
    step: 24,
    showTicksValues: true,
    stepsArray: this.verticalMarks,
    vertical: true,
    rightToLeft: true,
  };

  horizontalOptions: Options = {
    floor: 0,
    ceil: 816,
    step: 24,
    showTicksValues: true,
    stepsArray: this.horizontalMarks,
  };

  constructor(private store: Store) {}

  ngOnInit() {
    this.store.select(selectDocumentMargins).subscribe(margins => {
      console.log(margins);
      if (margins?.length) {
        this.verticalSlider = [-1 * (1056 - margins[1]), -1 * margins[0]];
        this.horizontalSlider = [margins[2], 816 - margins[3]];
      }
    });
  }

  onVerticalChange(event: ChangeContext) {
    let value = [event.value, event.highValue as number];
    this.verticalSlider = value;

    let margins = [...this.verticalSlider];
    margins[0] = Math.abs(value[1]);
    margins[1] = 1056 - Math.abs(value[0]);

    DOMEventHandlers.setPaperMargins(margins);
    this.store.dispatch(setDocumentMargins({ margins }));
  }

  onHorizontalChange(event: ChangeContext) {
    let value = [event.value, event.highValue as number];
    this.horizontalSlider = value;
    let margins = [...this.horizontalSlider];
    margins[2] = value[0];
    margins[3] = 816 - value[1];

    DOMEventHandlers.setPaperMargins(margins);
    this.store.dispatch(setDocumentMargins({ margins }));
  }
}

<!-- <div style="position: relative;"> -->
<!-- <lib-custom-slider-vertical [value]="verticalSlider.length ? verticalSlider : [-956, -100]" [min]="-1056" [max]="0"
    [marks]="verticalMarks" (change)="handleChange($event)" [step]="24" [size]="'small'"
    [slots]="{ thumb: MarginRightArrow }" valueLabelDisplay="off"></lib-custom-slider-vertical>
  <lib-custom-slider-horizontal [value]="horizontalSlider.length ? horizontalSlider : [120, 696]" [min]="0" [max]="816"
    [marks]="horizontalMarks" (change)="handleChangeHorizontal($event)" [step]="24" [size]="'small'"
    [slots]="{ thumb: MarginDownArrow }" valueLabelDisplay="off"></lib-custom-slider-horizontal> -->
<!-- </div> -->




<div class="margin-container">
  <!-- Vertical Ruler -->
  <div class="vertical-slider">
    <ngx-slider [(value)]="verticalSlider[0]" [(highValue)]="verticalSlider[1]" [options]="verticalOptions"
      (userChangeEnd)="onVerticalChange($event)">
    </ngx-slider>
  </div>

  <!-- Horizontal Ruler -->
  <div class="horizontal-line">
    <div class="horizontal-slider custom-slider ">
      <ngx-slider [(value)]="horizontalSlider[0]" [(highValue)]="horizontalSlider[1]" [options]="horizontalOptions"
        (userChangeEnd)="onHorizontalChange($event)">
      </ngx-slider>
    </div>
  </div>
</div>




<!-- <div class="ruler-container"> -->
<!-- <div class="ruler vertical">
    <mat-slider class="vertical-slider"  min="-1056"
    max="0"
    step="24" vertical="true" (input)="handleChange($event)"
      size="small">
      <input matSliderThumb [(ngModel)]="verticalSlider[0]">
    </mat-slider>
    <div *ngFor="let tick of verticalTicks; let i = index" class="tick vertical-tick" [style.top.px]="tick.value">
      <span class="tick-label">{{ tick.label }}</span>
    </div>
    <mat-slider class="vertical-slider v-end-slider" min="-1056"
    max="0"
    step="24" vertical="true"
      (input)="handleChange($event)">
      <input matSliderThumb [(ngModel)]="verticalSlider[1]">
    </mat-slider>
  </div> -->

<!-- <div class="ruler horizontal">
    <mat-slider class="horizontal-slider" horizontal="true" min="-816" max="0" (input)="handleChangeHorizontal($event)" step="24"
      showTickMarks>
      <input matSliderThumb [(ngModel)]="horizontalSlider[0]">
    </mat-slider>
    <div *ngFor="let tick of horizontalTicks; let i = index" class="tick horizontal-tick" [style.left.px]="tick.value">
      <span class="tick-label">{{ tick.label }}</span>
    </div>

    <mat-slider class="horizontal-slider h-end-slider" min="-816" max="0" (input)="handleChangeHorizontal($event)"
      size="small">
      <input matSliderThumb [(ngModel)]="horizontalSlider[1]">
    </mat-slider>
  </div>
</div> -->
